#! /bin/sh -e

export FCITX_ADDON_DIRS=/home/ccjmne/local/lib/fcitx5:/usr/lib/fcitx5
cmake -B build -DCMAKE_INSTALL_PREFIX=$HOME/local -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
case "$1" in
    client) fd '\.c$'   | entr -cr -- sh -c 'cmake --build build --target fkwhud-client && build/fkwhud' ;;
    server) fd '\.cpp$' | entr -cr -- sh -c 'cmake --build build --target fkwhud-server && cmake --install build --component server && fcitx5 -r' ;;
    *) echo >&2 "Usage: $0 <client|server>" ;;
esac
